DEFAULT_include = [
    'Multilayer Perceptron',
    'Nearest Neighbors',
    'SVM',
    'Linear SVM',
    'Decision Tree',
    'Random Forest',
    'Ada Boost',
    'Bagging',
    'Gradient Boost',
    'Logistic Regression',
    'Ridge Classification',
    'Ridge Classification CV',
    'Passive Aggressive',
    'Perceptron',
    'Guassian Naive Bayes',
    'Bernoulli Naive Bayes',
    'LDA',
    'QDA',
    'Gaussian Process',
    'Linear Regression',
    'Bayesian Ridge',
    'PassiveAggressiveRegressor',
    'GaussianProcessRegressor',
    'Ridge',
    'Lasso',
    'Lars',
    'LassoLars',
    'OrthogonalMatchingPursuit',
    'ElasticNet',
    'ARD Regression',
    'Huber Regression',
    'RANSAC Regression',
    'SGD Regression',
    'TheilSen Regression',
    'MLP Regression',
    'KNN Regression'
]
